# Generated by Django 5.0.2 on 2024-05-16 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("fname", models.CharField(default="", max_length=255)),
                ("lname", models.CharField(default="", max_length=255)),
                ("address", models.TextField(default="")),
                ("email", models.EmailField(default="", max_length=255)),
                ("password", models.TextField(default="")),
                ("contact", models.CharField(default="", max_length=20)),
                (
                    "profile",
                    models.ImageField(
                        default="SuperAdmin/dummy.jpg", upload_to="SuperAdmin/"
                    ),
                ),
                ("Otp", models.IntegerField(default=0)),
                ("OtpCount", models.IntegerField(default=0)),
                ("OtpStatus", models.BooleanField(default=False)),
                ("no_of_attempts_allowed", models.IntegerField(default=3)),
                ("no_of_wrong_attempts", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("email", models.EmailField(default="", max_length=255)),
                ("fname", models.CharField(default="", max_length=255)),
                ("lname", models.CharField(default="", max_length=255)),
                ("contact", models.CharField(default="", max_length=20)),
                ("street_address", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
                ("field_of_study", models.CharField(default="", max_length=255)),
                ("postal_code", models.CharField(default="", max_length=255)),
                ("address", models.TextField(default="")),
                ("password", models.TextField(default="")),
                ("level_of_education", models.TextField(default="")),
                ("Otp", models.IntegerField(default=0)),
                ("OtpCount", models.IntegerField(default=0)),
                ("OtpStatus", models.BooleanField(default=False)),
                ("no_of_attempts_allowed", models.IntegerField(default=3)),
                ("no_of_wrong_attempts", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ImageField(default="User/dummy.jpg", upload_to="User/"),
                ),
                ("resume", models.FileField(upload_to="User/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "job_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "company_location",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "employment_type",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "applicants",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "job_function",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "seniority_level",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "industries",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("links", models.TextField(blank=True, default="", null=True)),
                (
                    "job_description",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("company_url", models.TextField(blank=True, default="", null=True)),
                ("salary", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "listing_platform",
                    models.CharField(
                        choices=[("Indeed", "Indeed"), ("LinkedIn", "LinkedIn")],
                        max_length=250,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "city",
                            "job_title",
                            "company_name",
                            "company_location",
                            "employment_type",
                        ],
                        name="webapi_jobs_city_098417_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="userwhitelistToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="whitelistToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.superadmin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("Indeed", "Indeed"), ("LinkedIn", "LinkedIn")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.jobs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job_id")},
            },
        ),
        migrations.CreateModel(
            name="UserJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Indeed", "Indeed"), ("LinkedIn", "LinkedIn")],
                        max_length=50,
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.jobs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job_id")},
            },
        ),
    ]
