# Generated by Django 5.0.2 on 2024-05-29 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapi", "0004_alter_jobfeedback_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJobFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("feedback_text", models.TextField()),
                (
                    "job_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_job_feedbacks",
                        to="webapi.jobs",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "job_id")},
            },
        ),
    ]
